FROM alpine:3.20.3@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d

#RUN apk add bash=5.2.21-r0  # this breaks on alpine:3.20.x

RUN date > /build-date
CMD ["cat", "/build-date"]
